import type { CommandCenterData, Store, UserProfile } from "@/lib/types";

function dateOffset(daysAgo: number) {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString().slice(0, 10);
}

const demoUserId = "demo-user";
const demoStoreId = "demo-store";

export const sampleProfile: UserProfile = {
  id: demoUserId,
  email: "owner@example.com",
  full_name: "Demo Owner",
};

export const sampleStore: Store = {
  id: demoStoreId,
  user_id: demoUserId,
  name: "Main Street Market",
  address: "100 Main Street",
  city: "Springfield",
  state: "IL",
  zip: "62701",
};

export const sampleData: CommandCenterData = {
  daily_sales: [
    {
      id: "sale-1",
      user_id: demoUserId,
      store_id: demoStoreId,
      date: dateOffset(0),
      inside_sales: 5280,
      fuel_gallons_sold: 2210,
      fuel_retail_price: 3.59,
      fuel_cost_per_gallon: 3.32,
      lottery_sales: 980,
      lottery_payouts: 420,
      deli_sales: 840,
      cigarette_sales: 1380,
      beer_sales: 940,
      grocery_sales: 1220,
      other_sales: 920,
      notes: "Strong evening commute and lunch rush.",
    },
    {
      id: "sale-2",
      user_id: demoUserId,
      store_id: demoStoreId,
      date: dateOffset(1),
      inside_sales: 4860,
      fuel_gallons_sold: 1980,
      fuel_retail_price: 3.57,
      fuel_cost_per_gallon: 3.31,
      lottery_sales: 850,
      lottery_payouts: 380,
      deli_sales: 760,
      cigarette_sales: 1240,
      beer_sales: 880,
      grocery_sales: 1130,
      other_sales: 860,
      notes: "Restocked beer cave.",
    },
    {
      id: "sale-3",
      user_id: demoUserId,
      store_id: demoStoreId,
      date: dateOffset(2),
      inside_sales: 4550,
      fuel_gallons_sold: 1850,
      fuel_retail_price: 3.55,
      fuel_cost_per_gallon: 3.29,
      lottery_sales: 790,
      lottery_payouts: 310,
      deli_sales: 700,
      cigarette_sales: 1180,
      beer_sales: 820,
      grocery_sales: 1060,
      other_sales: 790,
      notes: null,
    },
    {
      id: "sale-4",
      user_id: demoUserId,
      store_id: demoStoreId,
      date: dateOffset(6),
      inside_sales: 6025,
      fuel_gallons_sold: 2425,
      fuel_retail_price: 3.61,
      fuel_cost_per_gallon: 3.34,
      lottery_sales: 1180,
      lottery_payouts: 470,
      deli_sales: 910,
      cigarette_sales: 1525,
      beer_sales: 1110,
      grocery_sales: 1320,
      other_sales: 980,
      notes: "Weekend promo lifted inside sales.",
    },
  ],
  expenses: [
    {
      id: "expense-1",
      user_id: demoUserId,
      store_id: demoStoreId,
      date: dateOffset(0),
      vendor_name: "Capital Candy",
      category: "Capital Candy",
      amount: 725.4,
      payment_method: "ACH",
      notes: "Candy and snacks delivery.",
    },
    {
      id: "expense-2",
      user_id: demoUserId,
      store_id: demoStoreId,
      date: dateOffset(1),
      vendor_name: "City Utilities",
      category: "Utilities",
      amount: 415.2,
      payment_method: "ACH",
      notes: null,
    },
    {
      id: "expense-3",
      user_id: demoUserId,
      store_id: demoStoreId,
      date: dateOffset(2),
      vendor_name: "Fuel Distributor",
      category: "Fuel purchase",
      amount: 6540,
      payment_method: "ACH",
      notes: "Regular fuel delivery.",
    },
  ],
  fuel_entries: [
    {
      id: "fuel-1",
      user_id: demoUserId,
      store_id: demoStoreId,
      date: dateOffset(0),
      gallons_sold: 2210,
      cost_per_gallon: 3.32,
      retail_price_per_gallon: 3.59,
      notes: "Margin held after nearby price move.",
    },
    {
      id: "fuel-2",
      user_id: demoUserId,
      store_id: demoStoreId,
      date: dateOffset(1),
      gallons_sold: 1980,
      cost_per_gallon: 3.31,
      retail_price_per_gallon: 3.57,
      notes: null,
    },
  ],
  lottery_entries: [
    {
      id: "lottery-1",
      user_id: demoUserId,
      store_id: demoStoreId,
      date: dateOffset(0),
      lottery_sales: 980,
      lottery_payouts: 420,
      commission_percentage: 6,
      notes: "Scratch-off display refreshed.",
    },
    {
      id: "lottery-2",
      user_id: demoUserId,
      store_id: demoStoreId,
      date: dateOffset(1),
      lottery_sales: 850,
      lottery_payouts: 380,
      commission_percentage: 6,
      notes: null,
    },
  ],
  deli_entries: [
    {
      id: "deli-1",
      user_id: demoUserId,
      store_id: demoStoreId,
      date: dateOffset(0),
      deli_sales: 840,
      food_cost: 315,
      waste_amount: 42,
      notes: "Breakfast sandwiches sold out.",
    },
    {
      id: "deli-2",
      user_id: demoUserId,
      store_id: demoStoreId,
      date: dateOffset(1),
      deli_sales: 760,
      food_cost: 288,
      waste_amount: 35,
      notes: null,
    },
  ],
  payroll_entries: [
    {
      id: "payroll-1",
      user_id: demoUserId,
      store_id: demoStoreId,
      employee_name: "Jordan Lee",
      date_range_start: dateOffset(6),
      date_range_end: dateOffset(0),
      hours_worked: 38.5,
      hourly_rate: 18,
      notes: "Shift lead.",
    },
    {
      id: "payroll-2",
      user_id: demoUserId,
      store_id: demoStoreId,
      employee_name: "Mia Patel",
      date_range_start: dateOffset(6),
      date_range_end: dateOffset(0),
      hours_worked: 32,
      hourly_rate: 16.5,
      notes: null,
    },
  ],
};
