"use client";

import { CircleHelp, Download, ExternalLink, X } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

const guides: Record<string, { title: string; intro: string; steps: string[]; links?: Array<{ label: string; href: string; download?: boolean }> }> = {
  "/onboarding": { title: "Store setup", intro: "Setup progress is calculated from saved data for the active store, so each location can be completed independently.", steps: ["Confirm store details and save recommended margins.", "Choose the POS profile that most closely matches your exports.", "Enter real data or add sample records only to empty modules."], links: [{ label: "Bulk CSV template", href: "/templates/bulk-daily-entry.csv", download: true }, { label: "Generic POS template", href: "/templates/generic-pos-import.csv", download: true }] },
  "/bulk-entry": { title: "Bulk monthly entry", intro: "Use one mode at a time. Preview spreadsheet or CSV rows before saving the month.", steps: ["Choose the month before entering values.", "Preview and resolve missing, duplicate, or invalid dates.", "Enable overwrite only when existing dates should be replaced."], links: [{ label: "Bulk CSV template", href: "/templates/bulk-daily-entry.csv", download: true }] },
  "/cash-reconciliation": { title: "Cash reconciliation", intro: "Reconcile the physical drawer, POS tenders, processor batch, and bank deposit for one business date.", steps: ["Pull expected totals from Daily Sales and POS imports.", "Enter drawer cash, drops, payouts, and processor totals.", "Resolve cash, card, and deposit variances before marking balanced."] },
  "/end-of-day-close": { title: "End-of-Day Close", intro: "Verify sales, tenders, fuel, lottery, and deposit readiness before locking the business date.", steps: ["Select the business date and review calculated checklist items.", "Mark lottery not applicable or bank deposit pending only when appropriate.", "Enter an override reason for unresolved variances, then close the day."] },
  "/bank-matching": { title: "Bank matching", intro: "Review suggested links between bank activity and store records.", steps: ["Review unmatched and suggested transactions.", "Approve strong matches or choose a manual record.", "Keep loans, owner draws, and transfers non-operating."] },
  "/fuel-reconciliation": { title: "Fuel reconciliation", intro: "Book inventory should match measured tank inventory within the grade threshold.", steps: ["Confirm beginning inventory and deliveries by grade.", "Pull sold gallons from POS or manual fuel entries.", "Review variance, actual margin, and suggested price before saving."] },
  "/smart-import": { title: "Smart Import", intro: "Every file stays in a reviewable batch with original parsed data and rollback history.", steps: ["Upload the statement, invoice, or report.", "Review low-confidence, duplicate, and unmapped rows.", "Confirm destinations before posting; use rollback if the batch was wrong."] },
  "/pos-integrations": { title: "POS integrations", intro: "Map only the columns present in the POS export. Missing optional fields can remain unmapped.", steps: ["Select the POS and a saved mapping profile.", "Upload CSV, inspect validation, and preview totals.", "Choose skip or overwrite for duplicates before saving."], links: [{ label: "Generic POS template", href: "/templates/generic-pos-import.csv", download: true }] },
  "/inventory": { title: "Inventory operations", intro: "Keep product cost, retail, on-hand quantity, and reorder levels current.", steps: ["Add or scan products and assign vendors.", "Receive purchase orders to update stock and vendor cost.", "Record shrink, damage, returns, and count corrections as adjustments."] },
  "/reports": { title: "Reporting center", intro: "Reports use Monthly Totals instead of daily rows for the same covered month to prevent duplicate sales.", steps: ["Select the store and reporting period.", "Include estimates for category-margin P&L or turn them off for tracked cost only.", "Use the accountant ZIP for supporting CSV schedules."], links: [{ label: "Open setup guide", href: "/onboarding" }] },
  "/dashboard": { title: "Daily owner workflow", intro: "Use the workflow panel to move from exceptions to the correct operating page.", steps: ["Complete the morning review before opening tasks.", "Reconcile the day after the POS close.", "Use weekly and month-end tabs for review and export work."] },
};

export function ContextHelp({ pathname }: { pathname: string }) {
  const [open, setOpen] = useState(false);
  const guide = guides[pathname] ?? { title: "Page help", intro: "Use the page header action to add data, then review saved records below.", steps: ["Confirm the active store before entering data.", "Complete required fields and review calculated values.", "Save and verify the new record appears in the list."] };

  return (
    <>
      <button aria-label="Open page help" className="rounded-lg border border-slate-200 bg-white p-2.5 text-slate-600 shadow-sm transition hover:border-cyan-300 hover:text-cyan-700" onClick={() => setOpen(true)} title="Page help" type="button"><CircleHelp className="h-4 w-4" /></button>
      {open ? <div className="fixed inset-0 z-[70] bg-slate-950/45" onClick={() => setOpen(false)} role="presentation"><aside aria-label="Page help" className="absolute inset-y-0 right-0 w-full max-w-md overflow-y-auto bg-white p-5 shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="flex items-start justify-between gap-4 border-b border-slate-200 pb-4"><div><p className="text-xs font-black uppercase text-cyan-700">Help</p><h2 className="mt-2 text-2xl font-black text-slate-950">{guide.title}</h2></div><button aria-label="Close page help" className="rounded-lg border border-slate-200 p-2 text-slate-500" onClick={() => setOpen(false)} type="button"><X className="h-5 w-5" /></button></div><p className="mt-5 text-sm leading-6 text-slate-600">{guide.intro}</p><ol className="mt-5 space-y-4">{guide.steps.map((step, index) => <li className="flex gap-3 text-sm leading-6 text-slate-700" key={step}><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-slate-950 text-xs font-black text-white">{index + 1}</span><span>{step}</span></li>)}</ol>{guide.links?.length ? <div className="mt-7 border-t border-slate-200 pt-5"><p className="text-xs font-black uppercase text-slate-500">Related</p><div className="mt-3 space-y-2">{guide.links.map((link) => link.download ? <a className="flex min-h-11 items-center justify-between rounded-lg border border-slate-200 px-3 text-sm font-bold text-slate-700" download href={link.href} key={link.href}>{link.label}<Download className="h-4 w-4" /></a> : <Link className="flex min-h-11 items-center justify-between rounded-lg border border-slate-200 px-3 text-sm font-bold text-slate-700" href={link.href} key={link.href} onClick={() => setOpen(false)}>{link.label}<ExternalLink className="h-4 w-4" /></Link>)}</div></div> : null}</aside></div> : null}
    </>
  );
}
